import type { Metadata } from "next";

import "./globals.css";
import { Providers } from "../components/Provider";

import TopNavParent from "@/components/layout/TopNavParent";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Providers>
          <TopNavParent />
          <main className="container  mx-auto">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
